Constrains
Arquisoft/dede_en2b pull request #23
Opened 2022-02-11 12:25 UTC by CarolinaUniovi

Constraints documentation is done as issued in #11 . Divided into two parts: technical and business constraints.

2022-02-11 15:56 UTC, UO277653 commented
From my part, after reviewing the changes I think that the commits can be merged.

2022-02-11 20:20 UTC, laura-pb requested changes
Overall is good, I just pointed out a typo and that maybe Github should be a technical constraint.

2022-02-11 20:20 UTC, laura-pb commented on docs/02_architecture_constraints.adoc
> +| _GitHub_|The code has to be deployed in GitHub, a public repository.
I feel like Github is more of a technical constraint rather than a business one, because it does not really affect architecture.

2022-02-11 20:30 UTC, UO277653 approved these changes
From my part, after reviewing the changes I think that the commits can be merged, so I approve it.

2022-02-13 22:16 UTC, laura-pb approved these changes
Everything fine!

2022-02-13 22:17 UTC, merged